[tool.poetry]
name = "minishell_v2"
version = "0.1.0"
description = ""
authors = ["budal-bi <budal-bi@student.42.fr>"]

[tool.poetry.dependencies]
python = "^3.7.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
